### PR TITLE
added a my_root module and fixed my_sum

### PR DESCRIPTION
**Pull request by StevenCHowell**

### CODE REVIEW

**Comment by dharhas** [comment]
hey looks good. next time do separate pull requests for each feature/ bugfix

also before I merge can you add tests for my_root and i think look at why the my_sum tests where passing

**Comment by StevenCHowell** [comment]
added them, have a look

**Comment by dharhas** [comment]
did the tests pass on your machine

**Comment by StevenCHowell** [comment]
actually, they don't
not sure why it fails to import `test_compute.py`.  I may have messed up the install.

```
(sprintdemo) [61] book: tests/> py.test
================================================================ test session starts ================================================================
platform darwin -- Python 2.7.12, pytest-2.8.5, py-1.4.31, pluggy-0.3.1
rootdir: /Users/schowell/sync/nrc/scipy2016/my_sprint_tutorial, inifile:
collected 0 items / 1 errors

====================================================================== ERRORS =======================================================================
______________________________________________ ERROR collecting sprint_tutorial/tests/test_compute.py _______________________________________________
test_compute.py:4: in <module>
    from sprint_tutorial.compute import my_sum, my_power
E   ImportError: No module named sprint_tutorial.compute
============================================================== 1 error in 0.01 seconds ==============================================================
```

**Comment by StevenCHowell** [comment]
from the python prompt, I can run the failed import without any problems:

```
(sprintdemo) [62] book: tests/> ipython
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:43:17)
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from sprint_tutorial.compute import my_sum

In [2]: from sprint_tutorial.compute import my_power
```

**Comment by dharhas** [comment]
hey you need to run python setup.py develop 

also pip install pytest

**Pull request merged**
